CREATE TABLE `resultados_mensais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lojaId` int NOT NULL,
	`mes` int NOT NULL,
	`ano` int NOT NULL,
	`zona` varchar(255),
	`totalServicos` int,
	`servicosPorColaborador` decimal(10,4),
	`numColaboradores` int,
	`objetivoDiaAtual` decimal(10,2),
	`objetivoMensal` int,
	`desvioObjetivoAcumulado` decimal(10,2),
	`desvioPercentualDia` decimal(5,4),
	`desvioPercentualMes` decimal(5,4),
	`taxaReparacao` decimal(5,4),
	`qtdReparacoes` int,
	`qtdParaBrisas` int,
	`gapReparacoes22` int,
	`nomeArquivo` varchar(255),
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `resultados_mensais_id` PRIMARY KEY(`id`)
);
