CREATE TABLE `vendas_complementares` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lojaId` int NOT NULL,
	`mes` int NOT NULL,
	`ano` int NOT NULL,
	`totalVendas` decimal(10,2),
	`escovasVendas` decimal(10,2),
	`escovasQtd` int,
	`escovasPercent` decimal(5,4),
	`polimentoQtd` int,
	`polimentoVendas` decimal(10,2),
	`tratamentoQtd` int,
	`tratamentoVendas` decimal(10,2),
	`outrosQtd` int,
	`outrosVendas` decimal(10,2),
	`peliculaVendas` decimal(10,2),
	`lavagensEcoExterior` int,
	`lavagensEcoNormal` int,
	`lavagensEcoFresh` int,
	`lavagensEcoProtecao` int,
	`lavagensEcoEstofos` int,
	`lavagensEcoTop` int,
	`lavagensTotal` int,
	`lavagensVendas` decimal(10,2),
	`nomeArquivo` varchar(255),
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendas_complementares_id` PRIMARY KEY(`id`)
);
