CREATE TABLE `nps_dados` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lojaId` int NOT NULL,
	`ano` int NOT NULL,
	`npsJan` decimal(5,4),
	`npsFev` decimal(5,4),
	`npsMar` decimal(5,4),
	`npsAbr` decimal(5,4),
	`npsMai` decimal(5,4),
	`npsJun` decimal(5,4),
	`npsJul` decimal(5,4),
	`npsAgo` decimal(5,4),
	`npsSet` decimal(5,4),
	`npsOut` decimal(5,4),
	`npsNov` decimal(5,4),
	`npsDez` decimal(5,4),
	`npsAnoTotal` decimal(5,4),
	`taxaRespostaJan` decimal(5,4),
	`taxaRespostaFev` decimal(5,4),
	`taxaRespostaMar` decimal(5,4),
	`taxaRespostaAbr` decimal(5,4),
	`taxaRespostaMai` decimal(5,4),
	`taxaRespostaJun` decimal(5,4),
	`taxaRespostaJul` decimal(5,4),
	`taxaRespostaAgo` decimal(5,4),
	`taxaRespostaSet` decimal(5,4),
	`taxaRespostaOut` decimal(5,4),
	`taxaRespostaNov` decimal(5,4),
	`taxaRespostaDez` decimal(5,4),
	`taxaRespostaAnoTotal` decimal(5,4),
	`nomeArquivo` varchar(255),
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nps_dados_id` PRIMARY KEY(`id`)
);
